Week 1 assessment tawnchan
learn-academy-2022-foxtrot/week-1-assessment-tawnchan pull request #1
Opened 2022-09-12 00:44 UTC by tawnchan

# Submitting Week 1 Assessment

### ✅ Completed Files

Select the following as confirmation that the files in this repository are complete.

- [✅  ] Coding Challenges
- [✅  ] Coding Concepts
- [ ✅ ] Interview Questions

### 📝 Feedback

If you would like specific feedback on a particular problem please leave details here:

I am not very good with wording, maybe overthinking it.

2022-09-12 21:01 UTC, elysemontano requested changes
Requesting changes: All researched answers must be formed in your own words.  I see several answers that are copied from sources.  Please change those problems to be worded in your own words and I will approve this assessment.

Other comments: Overall, you did a really great job on this assessment.  Your logic looks good in the code challenges, and it seems like you have a good understanding of the concepts.  Some of your interview answers were really thorough and others were very vague.  Make sure to expand on these questions as much as possible.  This is supposed to mimic an interview setting, and how you would respond to your interviewer.

2022-09-12 21:01 UTC, elysemontano commented on code-challenges.js
> +const boilingPoint = 212
Nice work here!

2022-09-12 21:01 UTC, elysemontano commented on code-challenges.js
> +} else {
Logic looks excellent.  To expand a little deeper, consider using the else as a catch-all for edge cases.  For instance, what if temp is a string?

2022-09-12 21:01 UTC, elysemontano commented on code-challenges.js
> +sanDiegoSummerTemperatures.sort(function(a, b){return b-a})
Awesome work on this!  I would like to see more explanation on what is happening with the sort function and what is being passed into it.

2022-09-12 21:01 UTC, elysemontano commented on coding-concepts.js
> +// b) Verify and explain: it did not... it returns an error saying .toUpperCase is not a function. I think its because it doesn't work on arrays.
Correct, .toUpperCase is a string method

2022-09-12 21:01 UTC, elysemontano commented on interview-questions.md
> +GitHub, Inc., is an Internet hosting service for software development and version control using Git. It provides the distributed version control of Git plus access control, bug tracking, software fea
Answers must be formed in your own words.

2022-09-12 21:01 UTC, elysemontano commented on interview-questions.md
> +Researched answer: i got the same..
A researched answer should expand and explain further on the concept.  In this case, there are several other operators that should be included in here and each one of these should be explained along with their operator name.

2022-09-12 21:01 UTC, elysemontano commented on interview-questions.md
> +Your answer: >, <, >=, <=, !=, !==, ==, ===.
Keep in mind, your answer is supposed to be a reflection of how you would respond if asked this question in an interview.  Using vocabulary and definitions as much as possible will help show your understanding and express interest in the job.

2022-09-12 21:01 UTC, elysemontano commented on interview-questions.md
> +good proper pair programming is communicating clearly the problem and objective of the solution and both figuring out how to do so using the available tools such as Github, Zoom and Slack. This way m
Really love this explanation!

2022-09-12 21:01 UTC, elysemontano commented on interview-questions.md
> +While reviewing, the observer also considers the "strategic" direction of the work, coming up with ideas for improvements and likely future problems to address. This is intended to free the driver to
Researched answers must be formed in your own words.

2022-09-12 23:40 UTC, tawnchan commented on code-challenges.js
> +} else {
Thanks for this.. Ari went this over with me also today.. i understand the idea now.

2022-09-12 23:43 UTC, tawnchan commented on interview-questions.md
> +GitHub, Inc., is an Internet hosting service for software development and version control using Git. It provides the distributed version control of Git plus access control, bug tracking, software fea
i gave my version of the answer on line 17

2022-09-14 03:00 UTC, tawnchan commented on interview-questions.md
> +Your answer: >, <, >=, <=, !=, !==, ==, ===.
Hi Elyse, i just redid the interview questions and pushed it up into the repo folder. do i do a pull request again? how do i notify you of these changes?  Thank you!

2022-09-14 20:31 UTC, elysemontano approved these changes
Great work on those changes!

2022-09-14 22:20 UTC, merged